---
name: Lint and Test

on:
  push:
    branches:
      - master
      - main

jobs:
  CheckoutPhase:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github }}
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."

      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."

  SetupPhase:
    runs-on: ubuntu-latest
    needs: [CheckoutPhase]
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: '14'

  BuildPhase:
    runs-on: ubuntu-latest
    needs: [SetupPhase]
    steps:
      - run: npm run build

  LintPhase:
    runs-on: ubuntu-latest
    needs: [BuildPhase]
    steps:
      - run: npm run lint --if-present

  TestPhase:
    runs-on: ubuntu-latest
    needs: [LintPhase]
    steps:
      - run: npm run test --if-present

  # PublishPhase:
  #   runs-on: ubuntu-latest
  #   needs: [TestPhase]
  #   if: startsWith(github.ref, 'refs/tags/v')
  #   steps:
  #     - run: npm run publish
