---
name: Publish Version

on:
  push:
    tags:
      - 'v*'
    branches:
      - master

jobs:
  BuildLintAndTest:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github }}
      - run: echo "üéâ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "üêß This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "üîé The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - run: echo "üí° The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo ${{ github.ref }}

      - name: Check out repository code
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        uses: actions/checkout@v2

      - name: Install node.js
        uses: actions/setup-node@v2
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'

      - run: npm ci
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}

      - run: npm run build
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}

      - run: npm run lint --if-present
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}

      - name: publish
        run: npm publish
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}

      - name: build docs
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        # if: success()
        run: npm run build:docs

      - name: cdk synth
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        # if: success()
        run: npm run cdk -- synth
        env:
          CICD: 'true'
          BRANCH: ${{ secrets.BRANCH }}
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.REGION }}
          AWS_REGION: ${{ secrets.REGION }}

      - name: cdk diff
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        # if: success()
        run: npm run cdk -- diff
        env:
          CICD: 'true'
          BRANCH: ${{ secrets.BRANCH }}
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.REGION }}
          AWS_REGION: ${{ secrets.REGION }}

      - name: cdk deploy
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        # if: success()
        run: npm run cdk -- deploy
        env:
          CICD: 'true'
          BRANCH: ${{ secrets.BRANCH }}
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.REGION }}
          AWS_REGION: ${{ secrets.REGION }}
